"""initial migration

Revision ID: 122116e6ffd5
Revises: 7262500816eb
Create Date: 2025-11-06 22:10:43.188327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122116e6ffd5'
down_revision: Union[str, Sequence[str], None] = '7262500816eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
