"""initial migration

Revision ID: 1aebf9488fcc
Revises: 2f93495b8f32
Create Date: 2025-11-09 00:23:54.021116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aebf9488fcc'
down_revision: Union[str, Sequence[str], None] = '2f93495b8f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_index('ix_users_is_deleted', ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_is_deleted')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
