"""initial migration

Revision ID: 1be24d15276d
Revises: 5147b3268969
Create Date: 2025-11-28 11:52:25.509105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be24d15276d'
down_revision: Union[str, Sequence[str], None] = '5147b3268969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chain_id', sa.String(length=64), nullable=True, comment='Celery 任务链 ID（chain.apply_async()返回的主任务 ID）'))
        batch_op.add_column(sa.Column('stage_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='任务在处理流程中的顺序（例如：0=上传, 1=提取, 2=向量化...）'))
        batch_op.add_column(sa.Column('parent_job_id', sa.UUID(), nullable=True, comment='任务链中的父任务 ID（业务依赖关系）'))
        batch_op.add_column(sa.Column('retry_of_job_id', sa.UUID(), nullable=True, comment='重试任务的原始任务 ID（重试逻辑）'))
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True, comment='触发任务的用户 ID（冗余字段，避免 JOIN documents 表）'))
        batch_op.alter_column('trace_id',
               existing_type=sa.VARCHAR(length=64),
               comment='请求追踪 ID（关联一次用户操作的所有任务）',
               existing_nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Celery 任务 ID（用户查询实时状态）',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_document_jobs_triggered_by'))
        batch_op.create_index(batch_op.f('ix_document_jobs_chain_id'), ['chain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_parent_job_id'), ['parent_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_retry_of_job_id'), ['retry_of_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('document_jobs_triggered_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'document_jobs', ['retry_of_job_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'document_jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('triggered_by')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('triggered_by', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('document_jobs_triggered_by_fkey'), 'document_jobs', ['triggered_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_document_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_retry_of_job_id'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_parent_job_id'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_chain_id'))
        batch_op.create_index(batch_op.f('ix_document_jobs_triggered_by'), ['triggered_by'], unique=False)
        batch_op.alter_column('task_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Celery 任务 ID（用户查询实时状态）',
               existing_nullable=True)
        batch_op.alter_column('trace_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='请求追踪 ID（关联一次用户操作的所有任务）',
               existing_nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('retry_of_job_id')
        batch_op.drop_column('parent_job_id')
        batch_op.drop_column('stage_order')
        batch_op.drop_column('chain_id')

    # ### end Alembic commands ###
