"""initial migration

Revision ID: 1dcff2c77974
Revises: 8d0662e4f66a
Create Date: 2025-11-21 06:14:48.834236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dcff2c77974'
down_revision: Union[str, Sequence[str], None] = '8d0662e4f66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_stage', sa.String(), server_default='pending', nullable=False, comment='处理阶段：待处理、提取文本、分块、向量化、存储向量、完成'))
        batch_op.add_column(sa.Column('processing_result', sa.String(), server_default='pending', nullable=False, comment='最终处理结果：成功、失败、部分成功等'))
        batch_op.add_column(sa.Column('processing_progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='处理进度详情：各阶段的开始时间、结束时间、状态、错误信息'))
        batch_op.alter_column('storage_status',
               existing_type=sa.VARCHAR(),
               server_default='uploading',
               comment='存储状态：上传中、已激活、已删除、已归档、已损坏等',
               existing_nullable=False)
        batch_op.alter_column('processing_status',
               existing_type=sa.VARCHAR(),
               comment='处理状态：等待中、处理中、成功、失败、超时',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='处理完成时间（任务完全完成）',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_documents_processing_result'), ['processing_result'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_processing_stage'), ['processing_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_storage_status'), ['storage_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_storage_status'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_stage'))
        batch_op.drop_index(batch_op.f('ix_documents_processing_result'))
        batch_op.alter_column('processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='处理完成时间（任务完全完成）',
               existing_nullable=True)
        batch_op.alter_column('processing_status',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='处理状态：等待中、处理中、成功、失败、超时',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('storage_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               comment=None,
               existing_comment='存储状态：上传中、已激活、已删除、已归档、已损坏等',
               existing_nullable=False)
        batch_op.drop_column('processing_progress')
        batch_op.drop_column('processing_result')
        batch_op.drop_column('processing_stage')

    # ### end Alembic commands ###
