"""initial migration

Revision ID: 2f93495b8f32
Revises: 122116e6ffd5
Create Date: 2025-11-07 23:34:06.816552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f93495b8f32'
down_revision: Union[str, Sequence[str], None] = '122116e6ffd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))

    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
