"""initial migration

Revision ID: 533f802658e7
Revises: 494f47b46e3e
Create Date: 2025-11-21 07:40:25.332237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533f802658e7'
down_revision: Union[str, Sequence[str], None] = '494f47b46e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vector_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('vector_chunks_document_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('vector_chunks_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vector_chunks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vector_chunks_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('vector_chunks_document_id_fkey'), 'documents', ['document_id'], ['id'])

    # ### end Alembic commands ###
