"""initial migration

Revision ID: 5d918d39afde
Revises: 9ec969dd43b7
Create Date: 2025-11-06 18:54:55.111419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d918d39afde'
down_revision: Union[str, Sequence[str], None] = '9ec969dd43b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chat_messages_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_messages_session_id_fkey'), 'chat_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
