"""initial migration

Revision ID: 7262500816eb
Revises: 5d918d39afde
Create Date: 2025-11-06 21:46:09.000646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7262500816eb'
down_revision: Union[str, Sequence[str], None] = '5d918d39afde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), nullable=True))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), nullable=True))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), nullable=True))

        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_constraint(batch_op.f('chat_sessions_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('trace_id',
               existing_type=sa.VARCHAR(length=64),
               comment='分布式追踪ID，用于日志链路分析',
               existing_nullable=True)
        batch_op.alter_column('version_id',
               existing_type=sa.VARCHAR(length=64),
               comment='对象存储中的版本ID',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_documents_task_id'))
        batch_op.drop_column('task_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               server_default='user',
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.create_index('ix_users_role', ['role'], unique=False)
        batch_op.create_index('ix_users_username_active', ['username', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username_active')
        batch_op.drop_index('ix_users_role')
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('version_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='对象存储中的版本ID',
               existing_nullable=True)
        batch_op.alter_column('trace_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='分布式追踪ID，用于日志链路分析',
               existing_nullable=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_sessions_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('client_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    with op.batch_alter_table('chat_calls', schema=None) as batch_op:
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
