"""initial migration

Revision ID: 9ba1d0bb63ea
Revises: 
Create Date: 2025-11-03 22:52:19.311630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ba1d0bb63ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('quota_tokens', sa.Integer(), nullable=False),
    sa.Column('used_tokens', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_email_active', ['email', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_chat_sessions_user_id', ['user_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('storage_status', sa.String(), server_default='active', nullable=False),
    sa.Column('processing_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('version_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_documents_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_file_extension'), ['file_extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index('ix_documents_processed_at', ['processed_at'], unique=False)
        batch_op.create_index('ix_documents_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('ix_documents_storage_key_prefix', ['storage_key'], unique=False, postgresql_ops={'storage_key': 'text_pattern_ops'})
        batch_op.create_index('ix_documents_task_id', ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_documents_user_status_created', ['user_id', 'storage_status', 'created_at'], unique=False)
        batch_op.create_index('ix_documents_user_storage_status', ['user_id', 'storage_status'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default='user', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('PARSE_PDF', 'OCR', 'EXTRACT_TEXT', 'EMEBED_DOCUMENT', 'CLASSIFY_CONTENT', 'GENERATE_PREVIEW', 'CONVERT_TO_WEB', 'VALEDATE_FILE', 'CHUNK_TEXT', name='document_job_type_enum'), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay_secs', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timeout_after_secs', sa.Integer(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_idempotent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_document_jobs_finished_at', ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index('ix_document_jobs_started_at', ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_document_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_document_jobs_task_id', ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_document_jobs_type_status', ['job_type', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_document_jobs_type_status')
        batch_op.drop_index(batch_op.f('ix_document_jobs_trace_id'))
        batch_op.drop_index('ix_document_jobs_task_id')
        batch_op.drop_index('ix_document_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_document_jobs_status'))
        batch_op.drop_index('ix_document_jobs_started_at')
        batch_op.drop_index(batch_op.f('ix_document_jobs_job_type'))
        batch_op.drop_index('ix_document_jobs_finished_at')
        batch_op.drop_index(batch_op.f('ix_document_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_created_at'))

    op.drop_table('document_jobs')
    op.drop_table('chat_messages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_user_storage_status')
        batch_op.drop_index('ix_documents_user_status_created')
        batch_op.drop_index(batch_op.f('ix_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_documents_trace_id'))
        batch_op.drop_index('ix_documents_task_id')
        batch_op.drop_index('ix_documents_storage_key_prefix', postgresql_ops={'storage_key': 'text_pattern_ops'})
        batch_op.drop_index('ix_documents_processing_status')
        batch_op.drop_index('ix_documents_processed_at')
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_file_extension'))
        batch_op.drop_index('ix_documents_deleted_at')
        batch_op.drop_index('ix_documents_created_at')

    op.drop_table('documents')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_sessions_user_id')

    op.drop_table('chat_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index('ix_users_email_active')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_users_deleted_at')

    op.drop_table('users')
    # ### end Alembic commands ###
