"""initial migration

Revision ID: a2bda8acc16a
Revises: ab435eebd79c
Create Date: 2025-12-06 06:14:47.778186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bda8acc16a'
down_revision: Union[str, Sequence[str], None] = 'ab435eebd79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_idempotent')
        batch_op.drop_column('retry_delay_secs')
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('timeout_after_secs')
        batch_op.drop_column('max_retries')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('timeout_after_secs', sa.INTEGER(), server_default=sa.text('600'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('attempt_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('retry_delay_secs', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_idempotent', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
