"""initial migration

Revision ID: ab435eebd79c
Revises: b0f3f32d3385
Create Date: 2025-11-30 08:07:38.921099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab435eebd79c'
down_revision: Union[str, Sequence[str], None] = 'b0f3f32d3385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('size_bytes',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('storage_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True,
               comment='对象存储中的唯一键（路径）')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('storage_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False,
               comment=None,
               existing_comment='对象存储中的唯一键（路径）')
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('size_bytes',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
