"""initial migration

Revision ID: b0f3f32d3385
Revises: 765c0b41b273
Create Date: 2025-11-28 22:54:56.192815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f3f32d3385'
down_revision: Union[str, Sequence[str], None] = '765c0b41b273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 步骤 1: 临时改为 TEXT 类型（绕过枚举限制）
    op.execute("ALTER TABLE document_jobs ALTER COLUMN job_type TYPE TEXT")
    
    # 步骤 2: 将所有数据转为小写
    op.execute("UPDATE document_jobs SET job_type = LOWER(job_type)")
    
    # 步骤 3: 删除旧枚举类型
    op.execute("DROP TYPE IF EXISTS document_job_type_enum CASCADE")
    
    # 步骤 4: 创建新的小写枚举类型
    op.execute("""
        CREATE TYPE document_job_type_enum AS ENUM (
            'upload_document',
            'delete_document',
            'move_document',
            'download_document',
            'export_document',
            'validate_file',
            'extract_text',
            'chunk_text',
            'embed_chunks',
            'classify_content',
            'generate_preview',
            'convert_to_web'
        )
    """)
    
    # 步骤 5: 将列改回枚举类型
    op.execute("""
        ALTER TABLE document_jobs 
        ALTER COLUMN job_type TYPE document_job_type_enum 
        USING job_type::document_job_type_enum
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
