"""initial migration

Revision ID: ccadf34e6630
Revises: b4c2b153d1e3
Create Date: 2025-09-24 12:30:51.089709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccadf34e6630'
down_revision: Union[str, Sequence[str], None] = 'b4c2b153d1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'uploaded'"),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_documents_storage_key'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.create_index('ix_documents_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_documents_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_unique_constraint(None, ['storage_key'])
        batch_op.drop_column('file_size')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_users_email_active', ['email', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email_active')
        batch_op.drop_index('ix_users_deleted_at')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('ix_documents_deleted_at')
        batch_op.drop_index('ix_documents_created_at')
        batch_op.create_index(batch_op.f('ix_documents_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_storage_key'), ['storage_key'], unique=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_column('size_bytes')

    # ### end Alembic commands ###
